// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// on boarding
export const ON_BOARDING_NAME = 'ON_BOARDING_NAME';
export const ON_BOARDING_BIRTH_DATE = 'ON_BOARDING_BIRTH_DATE';
export const ON_BOARDING_SKIP_NAME = 'ON_BOARDING_SKIP_NAME';
